#!/bin/bash

clear
echo "${bldgrn}I have changed your default shell to ${txtwht}/bin/zsh${txtrst}"
echo "${bldgrn}If you don't like it, change back to bash by running ${txtwht} echo \`whoami\` | xargs sudo usermod --shell /bin/zsh${txtrst}"

echo "Please log off now and log back in"
