#!/bin/bash +x

#cp -r bin ~/
#cp dotfiles/.* ~/
mkdir -p ~/local

sudo apt-get update
sudo apt-get install aptitude

echo `whoami` | xargs sudo usermod --shell /bin/zsh

./installers/install_packages
./installers/install_java
./installers/install_rvm
./installers/install_vim
./installers/install_imagemagick


# http://help.github.com/set-your-user-name-email-and-github-token/
#git config --global user.name "Firstname Lastname"
#git config --global user.email "your_email@youremail.com"
