#!/bin/bash +x

echo "${bldgrn}Copying programs into ${txtwht}$HOME/bin${txtrst}"
cp -r bin ~/
echo "${bldgrn}Installing shell config files${txtrst}"
cp -b dotfiles/.* ~/

sudo apt-get update
sudo apt-get install aptitude zsh

echo `whoami` | xargs sudo usermod --shell /bin/zsh

./installers/install_packages
./installers/install_java

#./installers/install_postgres

echo "${bldgrn}Installing software to local directory ${txtwht}$HOME/local${txtrst}"
mkdir -p ~/local
./installers/install_mongodb
./installers/install_rvm
./installers/install_vim
./installers/install_imagemagick

./installers/configure_setup
gnome-terminal 
exit
