#!/bin/bash +x

cp -r bin ~/
cp -r dotfiles/* ~/
mkdir -p ~/local

sudo apt-get update
sudo apt-get install aptitude

./installers/install_packages
./installers/install_imagemagick

echo `whoami` | xargs sudo usermod --shell /bin/zsh
#gem install hirb 

# http://help.github.com/set-your-user-name-email-and-github-token/
#git config --global user.name "Firstname Lastname"
#git config --global user.email "your_email@youremail.com"
