#!/bin/bash

curl -s -L https://github.com/sid137/shell_setup/tarball/master -o /tmp/shell-setup.tar.gz
rm -rf  /tmp/shell-setup
mkdir /tmp/shell-setup
tar -zxvf /tmp/shell-setup.tar.gz -C /tmp/shell-setup --strip 1
cd /tmp/shell-setup
./install
cd ..
rm -rf /tmp/shell-setup