#!/bin/bash

vim --version | grep 7.3 > /dev/null
if [ $? -ne 0 ]; then
    echo "${bldgrn}Installing the latest VIM editor into ${txtwht}$HOME/local/vim${txtrst}"
    if [ ! -d "/tmp/vim" ]; then
        hg clone https://vim.googlecode.com/hg/ ~/vim
    fi

    cd ~/vim

    make clean;
    ./configure --enable-rubyinterp --enable-perlinterp --enable-cscope --enable-multibyte  --with-features=huge --enable-fontset --enable-xim --with-x --prefix=$HOME/local/vim # --enable-pythoninterp --enable-python3interp 
    make; make install
    rm -rf ~/vim
fi

