#!/bin/bash

if [ ! -d "/tmp/vim" ]; then
    hg clone https://vim.googlecode.com/hg/ /tmp/vim
fi

cd /tmp/vim

make clean;
./configure --enable-rubyinterp --enable-perlinterp --enable-cscope --enable-multibyte  --with-features=huge --enable-fontset --enable-xim --with-x --prefix=$HOME/local/vim # --enable-pythoninterp --enable-python3interp 
make; make install

