#!/bin/bash

command -v identify
if [ $? -eq 1 ]; then
    wget -N --retr-symlinks ftp://ftp.imagemagick.org/pub/ImageMagick/ImageMagick.tar.gz
    tar -xzvf ImageMagick.tar.gz
    cd ImageMagick-*
    ./configure --prefix=$HOME/local/imagemagick
    make
    make install
    cd ..
    rm -rf ImageMagick-*
fi
