#!/bin/bash

rm -rf /tmp/vim
hg clone https://vim.googlecode.com/hg/ /tmp/vim
cd /tmp/vim

./configure --enable-rubyinterp --enable-pythoninterp --enable-perlinterp --enable-cscope --enable-multibyte  --with-features=huge --enable-fontset --enable-xim --with-x --prefix=$HOME/local/vim #--enable-python3interp 
make; make install

